local _, TFG = ...

TFG.WEAPON_SKILLS_FOREVER = {
    druid = {
        {
            id = 199,
            name = "Two-Handed Maces",
            icon = "inv_mace_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 15590,
            name = "Fist Weapons",
            icon = "inv_gauntlets_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
    hunter = {
        {
            id = 200,
            name = "Polearms",
            icon = "inv_spear_06",
            level = 20,
            source = {
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 197,
            name = "Two-Handed Axes",
            icon = "inv_axe_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 15590,
            name = "Fist Weapons",
            icon = "inv_gauntlets_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 202,
            name = "Two-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 196,
            name = "One-Handed Axes",
            icon = "inv_axe_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 264,
            name = "Bows",
            icon = "inv_weapon_bow_05",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 2567,
            name = "Thrown",
            icon = "inv_throwingknife_02",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 266,
            name = "Guns",
            icon = "inv_weapon_rifle_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 5011,
            name = "Crossbows",
            icon = "inv_weapon_crossbow_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
    mage = {
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 5009,
            name = "Wands",
            icon = "ability_shootwand",
        },
    },
    paladin = {
        {
            id = 200,
            name = "Polearms",
            icon = "inv_spear_06",
            level = 20,
            source = {
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 199,
            name = "Two-Handed Maces",
            icon = "inv_mace_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 197,
            name = "Two-Handed Axes",
            icon = "inv_axe_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 202,
            name = "Two-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 196,
            name = "One-Handed Axes",
            icon = "inv_axe_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
    priest = {
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 5009,
            name = "Wands",
            icon = "ability_shootwand",
        },
    },
    rogue = {
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 15590,
            name = "Fist Weapons",
            icon = "inv_gauntlets_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 264,
            name = "Bows",
            icon = "inv_weapon_bow_05",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 2567,
            name = "Thrown",
            icon = "inv_throwingknife_02",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 266,
            name = "Guns",
            icon = "inv_weapon_rifle_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 5011,
            name = "Crossbows",
            icon = "inv_weapon_crossbow_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
    shaman = {
        {
            id = 199,
            name = "Two-Handed Maces",
            icon = "inv_mace_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 197,
            name = "Two-Handed Axes",
            icon = "inv_axe_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 15590,
            name = "Fist Weapons",
            icon = "inv_gauntlets_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 196,
            name = "One-Handed Axes",
            icon = "inv_axe_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
    warlock = {
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 5009,
            name = "Wands",
            icon = "ability_shootwand",
        },
    },
    warrior = {
        {
            id = 200,
            name = "Polearms",
            icon = "inv_spear_06",
            level = 20,
            source = {
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 10000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 199,
            name = "Two-Handed Maces",
            icon = "inv_mace_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 197,
            name = "Two-Handed Axes",
            icon = "inv_axe_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 198,
            name = "One-Handed Maces",
            icon = "inv_mace_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 15590,
            name = "Fist Weapons",
            icon = "inv_gauntlets_04",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 202,
            name = "Two-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 196,
            name = "One-Handed Axes",
            icon = "inv_axe_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 264,
            name = "Bows",
            icon = "inv_weapon_bow_05",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 2567,
            name = "Thrown",
            icon = "inv_throwingknife_02",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
            },
        },
        {
            id = 227,
            name = "Staves",
            icon = "inv_staff_08",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Hanashi, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.5 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 201,
            name = "One-Handed Swords",
            icon = "ability_meleedamage",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 266,
            name = "Guns",
            icon = "inv_weapon_rifle_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Buliwyf Stonehand, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 61.3, y = 89.4 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ansekhwa, Thunder Bluff",
                    faction = "Horde",
                    position = { map = 1456, x = 41.1, y = 62.8 },
                },
            },
        },
        {
            id = 5011,
            name = "Crossbows",
            icon = "inv_weapon_crossbow_01",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
        {
            id = 1180,
            name = "Daggers",
            icon = "ability_steelmelee",
            source = {
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Woo Ping, Stormwind City",
                    faction = "Alliance",
                    position = { map = 1453, x = 63.9, y = 69 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Bixi Wobblebonk, Ironforge",
                    faction = "Alliance",
                    position = { map = 1455, x = 62.3, y = 89.7 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Ilyenia Moonfire, Darnassus",
                    faction = "Alliance",
                    position = { map = 1457, x = 57.4, y = 46.2 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Sayoc, Orgrimmar",
                    faction = "Horde",
                    position = { map = 1454, x = 81.5, y = 19.6 },
                },
                {
                    type = "Trainer",
                    cost = 1000,
                    location = "Archibald, Undercity",
                    faction = "Horde",
                    position = { map = 1458, x = 57.3, y = 32.3 },
                },
            },
        },
    },
}

TFG.WEAPON_SKILLS_FOREVER.__CONFIG = { mode = "class" }
